#!/bin/zsh
WAYBAR_NAME=hyprland-simple
env XDG_CURRENT_DESKTOP="Unity" waybar \
    -c ~/.config/waybar/$WAYBAR_NAME/config.jsonc \
    -s ~/.config/waybar/$WAYBAR_NAME/style.css &
env XDG_CURRENT_DESKTOP="Unity" waybar \
    -c ~/.config/waybar/$WAYBAR_NAME/config-bot.jsonc \
    -s ~/.config/waybar/$WAYBAR_NAME/style.css
